# Generated by Django 5.2.7 on 2025-11-24 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='მოდელი')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='ფოტო')),
                ('horsepower', models.IntegerField(verbose_name='ცხენის ძალა')),
                ('max_speed', models.IntegerField(verbose_name='მაქს. სიჩქარე (კმ/სთ)')),
                ('year', models.IntegerField(verbose_name='წელი')),
            ],
            options={
                'verbose_name': 'მანქანა',
                'verbose_name_plural': 'მანქანები',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'კალათის ნივთი',
                'verbose_name_plural': 'კალათის ნივთები',
            },
        ),
    ]
